import Link from 'next/link';
import type { Section } from '@/lib/countries';
import { RichText } from '../phase1/RichText';
import { resolveContentVariables } from '../../../../../packages/content-variables';
/* API-selected media can come from approved external asset hosts. */
/* eslint-disable @next/next/no-img-element */

const titles: Record<string, string> = { 'why-study': 'Why study here?', universities: 'Universities', subjects: 'Subjects and programmes', documents: 'Documents', scholarships: 'Scholarships', 'visa-process': 'Visa process', events: 'Events', cities: 'Cities', 'life-and-culture': 'Life and culture', careers: 'Careers', 'application-steps': 'Application steps', guides: 'Guides', 'trust-disclaimer': 'Source and trust note', 'consultant-cta': 'Plan with guidance', intakes: 'Intakes', 'cost-of-study': 'Cost of study', 'work-opportunities': 'Work opportunities', 'language-requirements': 'Language requirements' };
const safeHref = (value: string | null | undefined) => value && (/^\//.test(value) || /^#[a-zA-Z0-9_-]+$/.test(value) || /^https:\/\//.test(value)) ? value : '#consultation';
type EditorialVariables = Record<'countryName' | 'countrySlug', string>;
/* Section keys are author-written now, so one can arrive with spaces or
 * punctuation in it. The anchor and the nav entry pointing at it have to agree
 * on the same id, and it has to be usable in a URL fragment -- existing keys
 * are already slugs, so this leaves every one of them unchanged. */
const anchorId = (sectionKey: string) =>
  `country-section-${sectionKey.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'untitled'}`;
export function CountryEditorialSections({ sections, variables }: { sections: Section[]; variables: EditorialVariables }) { return <>{[...sections].sort((a, b) => a.displayOrder - b.displayOrder).map((section) => <EditorialSection key={section.id} section={section} variables={variables} />)}</>; }
export function editorialNavItems(sections: Section[]) { return [...sections].sort((a, b) => a.displayOrder - b.displayOrder).map((section) => ({ id: anchorId(section.sectionKey), label: section.heading ?? titles[section.sectionKey] ?? section.sectionKey })); }
function EditorialSection({ section, variables }: { section: Section; variables: EditorialVariables }) { const resolve = (value: string) => resolveVariables(value, variables); const title = resolve(section.heading ?? titles[section.sectionKey] ?? 'Country guidance'); const content = keyRenderer(section.sectionKey, section, resolve); return <article id={anchorId(section.sectionKey)} className={`editorial-section section-${section.sectionKey}`}><div className="section-heading">{section.eyebrow ? <p className="eyebrow">{resolve(section.eyebrow)}</p> : null}<h2>{title}</h2>{section.subheading ? <RichText className="section-lede" value={resolve(section.subheading)} /> : null}</div>{content}{section.primaryMedia ? <img className="section-media" src={section.primaryMedia.url} alt={section.primaryMedia.alt || title} /> : null}{section.ctaLabel ? <Link className="text-link" href={safeHref(section.ctaUrl)}>{resolve(section.ctaLabel)} →</Link> : null}</article>; }
function keyRenderer(key: string, section: Section, resolve: (value: string) => string) { const body = section.bodyJson ?? {}; if (key === 'application-steps' || key === 'visa-process') return <Steps items={body.items} resolve={resolve} />; if (key === 'documents') return <Checklist items={body.items} resolve={resolve} />; if (key === 'universities' || key === 'subjects' || key === 'scholarships' || key === 'events' || key === 'cities' || key === 'careers') return <Cards items={body.items} resolve={resolve} />; if (key === 'trust-disclaimer') return <Trust body={body} resolve={resolve} />; if (key === 'why-study' || key === 'life-and-culture' || key === 'guides' || key === 'work-opportunities' || key === 'language-requirements' || key === 'intakes' || key === 'cost-of-study' || key === 'consultant-cta') return <Copy body={body} resolve={resolve} />; return section.sectionType === 'STEPS' ? <Steps items={body.items} resolve={resolve} /> : section.sectionType === 'FACT_GRID' ? <Cards items={body.items} resolve={resolve} /> : section.sectionType === 'CARD_GRID' ? <Cards items={body.items} resolve={resolve} /> : section.sectionType === 'CTA' ? <Copy body={body} resolve={resolve} /> : section.sectionType === 'MEDIA' ? <RichText className="section-lede" value={resolve(string(body.caption))} /> : <Copy body={body} resolve={resolve} />; }
function string(value: unknown) { return typeof value === 'string' ? value : ''; }
function records(value: unknown) { return Array.isArray(value) ? value.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === 'object' && !Array.isArray(item))) : []; }
function resolveVariables(value: string, variables: EditorialVariables) {
  return resolveContentVariables('country', value, {
    name: variables.countryName,
    slug: variables.countrySlug,
  });
}
function Copy({ body, resolve }: { body: Record<string, unknown>; resolve: (value: string) => string }) { const paragraphs = Array.isArray(body.paragraphs) ? body.paragraphs.filter((item): item is string => typeof item === 'string') : [string(body.supportingText)]; return paragraphs.filter(Boolean).length ? <div className="editorial-copy">{paragraphs.filter(Boolean).map((paragraph, index) => <RichText key={`${paragraph.slice(0, 20)}-${index}`} value={resolve(paragraph)} />)}</div> : null; }
/* Descriptions are authored in the WYSIWYG, so they render as rich text. A
 * fact grid's `value` and anything imported as plain text still arrive here as
 * bare strings, which `RichText` renders as a paragraph unchanged. */
function Cards({ items, resolve }: { items: unknown; resolve: (value: string) => string }) { const values = records(items); return values.length ? <div className="editorial-items card-grid">{values.map((item, index) => <div key={`${string(item.title || item.label)}-${index}`}><strong>{resolve(string(item.title || item.label))}</strong><RichText value={resolve(string(item.description || item.value))} /></div>)}</div> : null; }
function Checklist({ items, resolve }: { items: unknown; resolve: (value: string) => string }) { const values = records(items); return values.length ? <ul className="editorial-checklist">{values.map((item, index) => <li key={`${string(item.title || item.label)}-${index}`}><strong>{resolve(string(item.title || item.label))}</strong><RichText value={resolve(string(item.description || item.value))} /></li>)}</ul> : null; }
function Steps({ items, resolve }: { items: unknown; resolve: (value: string) => string }) { const values = records(items); return values.length ? <ol className="editorial-steps">{values.map((item, index) => <li key={`${string(item.title)}-${index}`}><span>{resolve(string(item.step)) || String(index + 1).padStart(2, '0')}</span><div><strong>{resolve(string(item.title))}</strong><RichText value={resolve(string(item.description))} /></div></li>)}</ol> : null; }
function Trust({ body, resolve }: { body: Record<string, unknown>; resolve: (value: string) => string }) { return <div className="trust-notes"><RichText value={resolve(string(body.paragraph) || string(body.supportingText) || 'This editorial note is published separately from structured country profile verification.')} /></div>; }
