import type { EditorialSection } from '../catalog.types';

export const SECTION_KEYS = ['hero', 'why-study', 'universities', 'subjects', 'intakes', 'documents', 'cost-of-study', 'scholarships', 'visa-process', 'work-opportunities', 'language-requirements', 'events', 'cities', 'life-and-culture', 'living-costs', 'careers', 'application-steps', 'guides', 'faqs', 'consultant-cta', 'trust-disclaimer'] as const;
export const SECTION_TYPES = ['RICH_TEXT', 'FACT_GRID', 'CARD_GRID', 'STEPS', 'CTA', 'MEDIA'] as const;
export type SectionType = typeof SECTION_TYPES[number];
export type TypedRow = { label: string; value: string; description?: string; step?: string };
export type TypedBody = { paragraphs?: string[]; items?: TypedRow[]; supportingText?: string; caption?: string };
export type SectionDraft = { sectionKey: string; sectionType: SectionType; eyebrow: string; heading: string; subheading: string; body: TypedBody; primaryMediaId: string; secondaryMediaId: string; ctaLabel: string; ctaUrl: string; displayOrder: number; status: string };
export const blankSection: SectionDraft = { sectionKey: '', sectionType: 'RICH_TEXT', eyebrow: '', heading: '', subheading: '', body: { paragraphs: [''] }, primaryMediaId: '', secondaryMediaId: '', ctaLabel: '', ctaUrl: '', displayOrder: 0, status: 'ACTIVE' };
export const blankFaq = { question: '', answer: '', category: '', isFeatured: false, status: 'ACTIVE', displayOrder: 0 };
export const blankSeo = { seoTitle: '', metaDescription: '', canonicalUrl: '', focusKeyword: '', ogTitle: '', ogDescription: '', ogMediaId: '', twitterTitle: '', twitterDescription: '', twitterMediaId: '', robotsIndex: true, robotsFollow: true, schemaJson: '', hreflangJson: '' };
export const blankCard = { title: '', slug: '', shortDescription: '', overview: '', iconMediaId: '', featuredMediaId: '', isFreeConsultation: true, ctaLabel: 'View consultants', ctaUrl: '', status: 'DRAFT', isFeatured: false, displayOrder: 0 };
export function draftFromSection(section: EditorialSection): SectionDraft { const body = section.bodyJson ?? {}; const typedBody: TypedBody = { paragraphs: Array.isArray(body.paragraphs) ? body.paragraphs.filter((item): item is string => typeof item === 'string') : undefined, items: Array.isArray(body.items) ? body.items.map((item): TypedRow => { const row = item && typeof item === 'object' ? item as Record<string, unknown> : {}; return { label: String(row.label ?? row.title ?? ''), value: String(row.value ?? ''), description: String(row.description ?? ''), step: String(row.step ?? '') }; }) : undefined, supportingText: typeof body.supportingText === 'string' ? body.supportingText : undefined, caption: typeof body.caption === 'string' ? body.caption : undefined }; return { sectionKey: section.sectionKey, sectionType: SECTION_TYPES.includes(section.sectionType as SectionType) ? section.sectionType as SectionType : 'RICH_TEXT', eyebrow: section.eyebrow ?? '', heading: section.heading ?? '', subheading: section.subheading ?? '', body: typedBody, primaryMediaId: section.primaryMedia?.id ?? '', secondaryMediaId: section.secondaryMedia?.id ?? '', ctaLabel: section.ctaLabel ?? '', ctaUrl: section.ctaUrl ?? '', displayOrder: section.displayOrder, status: section.status }; }
export function bodyForApi(draft: SectionDraft): Record<string, unknown> { if (draft.sectionType === 'RICH_TEXT') return { paragraphs: (draft.body.paragraphs ?? []).map((item) => item.trim()).filter(Boolean) }; if (draft.sectionType === 'CTA') return { supportingText: draft.body.supportingText?.trim() ?? '' }; if (draft.sectionType === 'MEDIA') return { caption: draft.body.caption?.trim() ?? '' }; return { items: (draft.body.items ?? []).filter((row) => row.label.trim() || row.value.trim() || row.description?.trim()).map((row) => draft.sectionType === 'FACT_GRID' ? { label: row.label.trim(), value: row.value.trim() } : draft.sectionType === 'STEPS' ? { step: row.step?.trim() || '', title: row.label.trim(), description: row.description?.trim() || row.value.trim() } : { title: row.label.trim(), description: row.description?.trim() || row.value.trim() }) }; }
