import { html } from './content';

export type SubjectFacts = {
  name: string;
  slug: string;
  /** What the field is, in one sentence. */
  blurb: string;
  /** What studying it actually involves. */
  studying: string;
  /** Who it suits. */
  suits: string;
  /** Where it leads. */
  leads: string;
  featured?: boolean;
};

export type SpecFacts = {
  name: string;
  slug: string;
  subject: string;
  blurb: string;
  detail: string;
};

export type CourseFacts = {
  name: string;
  slug: string;
  subject: string;
  spec?: string;
  level: 'UG' | 'PG' | 'MBA' | 'PGDM' | 'PHD' | 'DIPLOMA' | 'CERTIFICATE';
  qualification: string;
  shortName?: string;
  durationMin: number;
  durationMax: number;
  /** What the degree covers. */
  covers: string;
  /** What the work is like. */
  work: string;
  /** Where graduates go. */
  careers: string;
  modes?: ('FULL_TIME' | 'PART_TIME' | 'ONLINE' | 'HYBRID')[];
  featured?: boolean;
};

export function subjectOverview(s: SubjectFacts): string {
  return html([
    s.blurb,
    '## What you actually study',
    s.studying,
    '## Who it suits',
    s.suits,
    '## Where it leads',
    s.leads,
    'Programmes in this field differ considerably between institutions, so compare the module lists and the balance of theory to practice rather than relying on the degree title alone.',
  ]);
}

export function courseOverview(c: CourseFacts): string {
  return html([
    c.covers,
    '## How the programme runs',
    c.work,
    `A ${c.qualification} of this kind typically runs ${c.durationMin === c.durationMax ? `${c.durationMin} year${c.durationMin === 1 ? '' : 's'}` : `${c.durationMin} to ${c.durationMax} years`} full time, though the exact structure, credit weighting and assessment pattern are set by each institution.`,
    '## Careers',
    c.careers,
    'Entry requirements are set by the institution and often by the individual programme, so check them against the specific course you intend to apply for rather than assuming the subject has one standard.',
  ]);
}

export const SUBJECTS: SubjectFacts[] = [
  {
    name: 'Computer Science', slug: 'computer-science', featured: true,
    blurb: 'Computer science is the study of computation itself — what can be computed, how efficiently, and how to build systems that do it reliably.',
    studying: 'The core is algorithms, data structures, the theory of computation, operating systems, networks and databases, taught alongside a great deal of programming. Most degrees then widen into artificial intelligence, security, graphics, distributed systems or human-computer interaction. The mathematics is real and unavoidable: discrete mathematics, probability and linear algebra underpin almost everything above them.',
    suits: 'People who enjoy breaking a problem into parts and are willing to sit with something that does not work until it does. Prior programming experience helps but is rarely required; comfort with abstraction matters more.',
    leads: 'Software engineering, data and machine learning, security, infrastructure and research, across essentially every industry rather than only technology companies.',
  },
  {
    name: 'Engineering', slug: 'engineering', featured: true,
    blurb: 'Engineering applies physics and mathematics to build things that work, safely and within constraints of cost, material and time.',
    studying: 'A shared foundation of mechanics, materials, thermodynamics, mathematics and electrical principles, followed by specialisation into mechanical, civil, electrical, chemical, aerospace or another branch. Laboratory work, design projects and a substantial final-year project are standard, and most programmes include work closely modelled on professional practice.',
    suits: 'People who want to build and are comfortable with quantitative work and physical constraints. Engineering rewards precision and patience with detail more than flashes of insight.',
    leads: 'Design, manufacturing, construction, energy, aerospace, automotive and consulting, with professional registration available in most countries after a period of supervised practice.',
  },
  {
    name: 'Business and Management', slug: 'business-and-management', featured: true,
    blurb: 'Business and management is the study of how organisations are financed, run, staffed and grown — and why so many of them fail at it.',
    studying: 'Accounting, finance, marketing, operations, strategy and organisational behaviour form the core, taught heavily through case studies and group work. Most programmes then allow specialisation, and many include a consulting project with a real organisation.',
    suits: 'People who like working with others, are comfortable presenting an argument, and want breadth rather than a single technical depth. Group work is unavoidable, so it suits those who can manage it rather than resent it.',
    leads: 'Consulting, finance, marketing, operations, general management and entrepreneurship. It is also the most common route for technical graduates moving towards management.',
  },
  {
    name: 'Data Science and Analytics', slug: 'data-science-and-analytics', featured: true,
    blurb: 'Data science sits between statistics, computing and the domain you are applying it to, and the third of those is the part most often underestimated.',
    studying: 'Statistics and probability, machine learning, programming, data engineering and visualisation, usually with a strong project component using real and therefore messy data. Good programmes spend real time on experimental design and on the limits of inference, not only on model fitting.',
    suits: 'People comfortable with mathematics who also want to work on concrete problems. It suits those who find the question of what the data can honestly support more interesting than the tooling.',
    leads: 'Data science, analytics, machine learning engineering, quantitative research and product analytics, across finance, health, retail, government and technology.',
  },
  {
    name: 'Health and Medicine', slug: 'health-and-medicine', featured: true,
    blurb: 'Health and medicine covers clinical practice and the sciences and systems that support it — from molecular biology to how a health service is organised.',
    studying: 'Anatomy, physiology, biochemistry and pharmacology underpin the clinical subjects, with substantial supervised practice in hospitals and clinics for practitioner programmes. Non-clinical routes concentrate instead on epidemiology, public health, health policy and biomedical research.',
    suits: 'People prepared for long programmes with heavy content and real responsibility. Clinical routes in particular demand resilience and an ability to work with people at difficult moments.',
    leads: 'Clinical practice, nursing, pharmacy, public health, health policy, biomedical research and the pharmaceutical industry. Practitioner routes require registration with the relevant professional body in the country you intend to work in.',
  },
  {
    name: 'Law', slug: 'law', featured: true,
    blurb: 'Law is the study of the rules societies make, how they are interpreted, and how they are argued about.',
    studying: 'Contract, tort, criminal, constitutional and property law form the foundation, taught through cases and statutes, with a heavy emphasis on reading, precise writing and oral argument. Later study specialises into commercial, international, human rights, intellectual property or another field.',
    suits: 'People who read quickly and closely, write precisely, and enjoy constructing an argument and defending it against a good counter-argument.',
    leads: 'Legal practice, corporate and in-house counsel, policy, compliance, international organisations and the judiciary. Note that qualifying to practise is jurisdiction-specific and usually requires further local examinations.',
  },
  {
    name: 'Design and Creative Arts', slug: 'design-and-creative-arts', featured: true,
    blurb: 'Design and the creative arts are taught through making: the work is produced, shown, criticised and remade.',
    studying: 'Studio practice is the centre of it, supported by history, theory and technical skills. Assessment is largely on a portfolio built across the degree, and the critique — presenting work for structured criticism — is the defining method of teaching.',
    suits: 'People who can take criticism of their work without taking it personally, and who are willing to make many bad versions on the way to a good one. A portfolio is usually part of admission.',
    leads: 'Graphic and communication design, product and interaction design, animation, film, fashion and illustration, in studios, agencies, in-house teams and independent practice.',
  },
  {
    name: 'Natural Sciences', slug: 'natural-sciences',
    blurb: 'The natural sciences ask how the physical and living world works, and test the answers by experiment.',
    studying: 'Physics, chemistry, mathematics, biology and the earth and environmental sciences, taught with substantial laboratory and field work and a strong mathematical foundation. Most degrees culminate in an independent research project.',
    suits: 'People driven by the question itself rather than its application, and comfortable with mathematics and with experiments that do not work the first time.',
    leads: 'Research and doctoral study, laboratory and industrial science, energy, environmental consultancy, data analysis and teaching.',
  },
  {
    name: 'Social Sciences', slug: 'social-sciences',
    blurb: 'The social sciences study how people behave individually and collectively, and how the institutions they build shape both.',
    studying: 'Economics, psychology, sociology, politics and international relations, taught through a mixture of theory, empirical method and close reading. Quantitative method is now central to most of these fields, and statistics is a standard part of the training.',
    suits: 'People interested in why things happen rather than only what happened, and willing to work with evidence that is messy and contested.',
    leads: 'Policy, research, government, international organisations, consultancy, market research, journalism and further academic study.',
  },
  {
    name: 'Architecture and Built Environment', slug: 'architecture-and-built-environment',
    blurb: 'Architecture and the built environment cover the design, planning, construction and management of the places people live and work in.',
    studying: 'Design studio is the core, supported by structures, environmental systems, history and construction technology. Projects run long, assessment is by portfolio and review, and the studio culture is intense.',
    suits: 'People who can hold a creative idea and a technical constraint at the same time, and who are prepared for long programmes — professional qualification in architecture usually takes considerably longer than a single degree.',
    leads: 'Architectural practice, urban planning, construction and project management, landscape architecture and sustainability consultancy.',
  },
];

export const SPECIALIZATIONS: SpecFacts[] = [
  { name: 'Artificial Intelligence', slug: 'artificial-intelligence', subject: 'computer-science', blurb: 'Building systems that perform tasks which would ordinarily require human judgement.', detail: 'Covers search, knowledge representation, reasoning under uncertainty and the machine learning methods that now dominate the field, alongside the ethical and safety questions that come with deploying them.' },
  { name: 'Machine Learning', slug: 'machine-learning', subject: 'computer-science', blurb: 'The statistical methods by which systems improve at a task from data rather than explicit instruction.', detail: 'Supervised, unsupervised and reinforcement learning, deep neural networks, and the practical questions of generalisation, evaluation and bias that separate a working model from a demonstration.' },
  { name: 'Cybersecurity', slug: 'cybersecurity', subject: 'computer-science', blurb: 'Protecting systems, networks and data from adversaries who are actively trying to defeat you.', detail: 'Cryptography, network and systems security, secure software development, incident response and the legal and governance frameworks around them. Good programmes teach attack as well as defence, because you cannot defend what you do not understand.' },
  { name: 'Software Engineering', slug: 'software-engineering', subject: 'computer-science', blurb: 'The discipline of building software that a team can maintain and a business can depend on.', detail: 'Requirements, architecture, design patterns, testing, version control, continuous delivery and the human process of working in a team — the parts of the job that distinguish a codebase from a program.' },
  { name: 'Computer Networks and Distributed Systems', slug: 'computer-networks-and-distributed-systems', subject: 'computer-science', blurb: 'How independent machines communicate and cooperate reliably despite failure.', detail: 'Protocols, routing, concurrency, consistency, fault tolerance and the design of systems that keep working when parts of them do not.' },
  { name: 'Human-Computer Interaction', slug: 'human-computer-interaction', subject: 'computer-science', blurb: 'Designing and evaluating systems around how people actually behave rather than how designers assume they do.', detail: 'Interaction design, usability evaluation, accessibility, cognitive psychology and user research methods, with a strong emphasis on testing designs with real people.' },
  { name: 'Mechanical Engineering', slug: 'mechanical-engineering', subject: 'engineering', blurb: 'The design and analysis of machines and mechanical systems.', detail: 'Statics and dynamics, thermodynamics, fluid mechanics, materials and manufacturing, with computer-aided design and substantial laboratory work throughout.' },
  { name: 'Electrical and Electronic Engineering', slug: 'electrical-and-electronic-engineering', subject: 'engineering', blurb: 'From power systems at national scale down to the circuits inside a single chip.', detail: 'Circuit theory, signals and systems, electromagnetics, control, power electronics and embedded systems, with laboratory work throughout.' },
  { name: 'Civil Engineering', slug: 'civil-engineering', subject: 'engineering', blurb: 'The design and construction of infrastructure — bridges, buildings, water systems, transport.', detail: 'Structural analysis, geotechnics, hydraulics, transportation and construction management, with a strong emphasis on codes, safety factors and professional responsibility.' },
  { name: 'Chemical Engineering', slug: 'chemical-engineering', subject: 'engineering', blurb: 'Turning chemical processes that work in a flask into processes that work at industrial scale.', detail: 'Mass and energy balances, transport phenomena, reaction engineering, separation processes, process control and plant design, with a large design project typical in the final year.' },
  { name: 'Aerospace Engineering', slug: 'aerospace-engineering', subject: 'engineering', blurb: 'The design of aircraft and spacecraft, where weight and failure both carry unusual penalties.', detail: 'Aerodynamics, propulsion, flight mechanics, structures and control, usually with wind tunnel work and a substantial design project.' },
  { name: 'Robotics and Mechatronics', slug: 'robotics-and-mechatronics', subject: 'engineering', blurb: 'Where mechanical design, electronics and software meet in a machine that senses and acts.', detail: 'Kinematics, sensors and actuators, embedded control, computer vision and motion planning, taught almost entirely through building things that move.' },
  { name: 'Finance', slug: 'finance', subject: 'business-and-management', blurb: 'How capital is raised, allocated, priced and risked.', detail: 'Corporate finance, valuation, capital markets, derivatives, portfolio theory and risk management, with substantial quantitative content in most programmes.' },
  { name: 'Marketing', slug: 'marketing', subject: 'business-and-management', blurb: 'Understanding what people want, and how a product reaches them.', detail: 'Consumer behaviour, market research, brand strategy, pricing, digital channels and analytics, taught largely through cases and live projects.' },
  { name: 'Supply Chain and Operations', slug: 'supply-chain-and-operations', subject: 'business-and-management', blurb: 'The movement of goods and the design of the processes that produce them.', detail: 'Operations strategy, logistics, inventory and demand planning, procurement, quality management and the modelling techniques used to optimise them.' },
  { name: 'International Business', slug: 'international-business', subject: 'business-and-management', blurb: 'Running an organisation across borders, legal systems and cultures.', detail: 'Trade, foreign market entry, cross-cultural management, international finance and the regulatory environments that constrain all of them.' },
  { name: 'Entrepreneurship and Innovation', slug: 'entrepreneurship-and-innovation', subject: 'business-and-management', blurb: 'Starting a venture, and building the capacity for renewal inside an existing organisation.', detail: 'Opportunity identification, business modelling, venture finance, intellectual property and growth, usually assessed through developing an actual venture proposition.' },
  { name: 'Human Resource Management', slug: 'human-resource-management', subject: 'business-and-management', blurb: 'How organisations recruit, develop, reward and retain the people who work in them.', detail: 'Employment relations, organisational behaviour, reward and performance systems, employment law and workforce analytics.' },
  { name: 'Business Analytics', slug: 'business-analytics', subject: 'data-science-and-analytics', blurb: 'Applying analytical method to decisions a business actually has to make.', detail: 'Statistical modelling, forecasting, optimisation, visualisation and the communication of an analytical result to people who will act on it without reading the appendix.' },
  { name: 'Applied Statistics', slug: 'applied-statistics', subject: 'data-science-and-analytics', blurb: 'The theory and practice of drawing defensible conclusions from data.', detail: 'Inference, regression, experimental design, Bayesian methods, survival analysis and computational statistics, with an emphasis on knowing what a method assumes.' },
  { name: 'Big Data Engineering', slug: 'big-data-engineering', subject: 'data-science-and-analytics', blurb: 'Building the pipelines and storage that make analysis possible at scale.', detail: 'Distributed storage and processing, streaming systems, data modelling, orchestration and the operational discipline of keeping a pipeline running.' },
  { name: 'Bioinformatics', slug: 'bioinformatics', subject: 'data-science-and-analytics', blurb: 'Computational methods applied to biological data, particularly genomic data.', detail: 'Sequence analysis, genomics, structural biology, statistical genetics and the programming and pipeline skills needed to handle datasets of that size.' },
  { name: 'Public Health', slug: 'public-health', subject: 'health-and-medicine', blurb: 'The health of populations rather than individual patients.', detail: 'Epidemiology, biostatistics, health policy, environmental health and health promotion, with a strong quantitative core and a substantial practical or research project.' },
  { name: 'Nursing', slug: 'nursing', subject: 'health-and-medicine', blurb: 'Direct clinical care, and the largest profession in most health systems.', detail: 'Anatomy and physiology, pharmacology, clinical skills and evidence-based practice, with a very large proportion of the programme spent in supervised clinical placement.' },
  { name: 'Pharmacy and Pharmaceutical Sciences', slug: 'pharmacy-and-pharmaceutical-sciences', subject: 'health-and-medicine', blurb: 'How medicines are discovered, formulated, regulated and used safely.', detail: 'Medicinal chemistry, pharmacology, pharmaceutics, pharmacy practice and regulatory affairs, with laboratory and placement work throughout.' },
  { name: 'Biomedical Science', slug: 'biomedical-science', subject: 'health-and-medicine', blurb: 'The laboratory science that underpins diagnosis and treatment.', detail: 'Cell biology, immunology, microbiology, genetics and clinical biochemistry, with extensive laboratory training and a research project.' },
  { name: 'Physiotherapy and Rehabilitation', slug: 'physiotherapy-and-rehabilitation', subject: 'health-and-medicine', blurb: 'Restoring movement and function after injury, illness or surgery.', detail: 'Musculoskeletal, neurological and cardiorespiratory practice, exercise science and manual therapy, with substantial supervised clinical placement.' },
  { name: 'International Law', slug: 'international-law', subject: 'law', blurb: 'The law that operates between states, and increasingly between states and individuals.', detail: 'Treaty law, international institutions, dispute resolution, humanitarian and criminal law, and the persistent question of how any of it is enforced.' },
  { name: 'Commercial and Corporate Law', slug: 'commercial-and-corporate-law', subject: 'law', blurb: 'The legal framework within which businesses are formed, financed and traded.', detail: 'Company law, contract, mergers and acquisitions, competition law, insolvency and financial regulation.' },
  { name: 'Human Rights Law', slug: 'human-rights-law', subject: 'law', blurb: 'The legal protection of individuals against the power of states and institutions.', detail: 'International and regional human rights instruments, enforcement mechanisms, refugee and asylum law, and the practice of litigation and advocacy.' },
  { name: 'Intellectual Property Law', slug: 'intellectual-property-law', subject: 'law', blurb: 'The law governing ownership of inventions, brands, designs and creative work.', detail: 'Patents, trade marks, copyright and design rights, licensing, and the tension between protection and access that runs through the whole field.' },
  { name: 'Graphic and Communication Design', slug: 'graphic-and-communication-design', subject: 'design-and-creative-arts', blurb: 'Making information clear, persuasive and worth looking at.', detail: 'Typography, layout, identity, editorial and digital design, taught through studio projects and assessed on a portfolio built over the degree.' },
  { name: 'Interaction and User Experience Design', slug: 'interaction-and-user-experience-design', subject: 'design-and-creative-arts', blurb: 'Designing digital products around how people actually use them.', detail: 'User research, information architecture, prototyping, interface design and usability testing, with a portfolio of case studies as the main output.' },
  { name: 'Animation and Visual Effects', slug: 'animation-and-visual-effects', subject: 'design-and-creative-arts', blurb: 'Bringing images to life, by hand and by computation.', detail: 'Drawing and movement fundamentals, 3D modelling, rigging, lighting, compositing and the pipeline discipline of a production studio.' },
  { name: 'Fashion Design', slug: 'fashion-design', subject: 'design-and-creative-arts', blurb: 'Designing and making garments, from the first sketch to the finished pattern.', detail: 'Pattern cutting, construction, textiles, illustration and collection development, culminating in a final collection shown publicly.' },
  { name: 'Film and Media Production', slug: 'film-and-media-production', subject: 'design-and-creative-arts', blurb: 'Telling stories in moving image, and running the production that makes them.', detail: 'Directing, cinematography, sound, editing and production management, taught largely by making films in crews.' },
  { name: 'Physics', slug: 'physics', subject: 'natural-sciences', blurb: 'The search for the rules the physical world runs on.', detail: 'Classical and quantum mechanics, electromagnetism, thermodynamics, statistical physics and relativity, with laboratory work and a heavy mathematical foundation.' },
  { name: 'Chemistry', slug: 'chemistry', subject: 'natural-sciences', blurb: 'The study of matter, its structure, and the transformations it undergoes.', detail: 'Organic, inorganic, physical and analytical chemistry, with very substantial laboratory work and a research project in the final year.' },
  { name: 'Mathematics', slug: 'mathematics', subject: 'natural-sciences', blurb: 'The study of structure, quantity and change — and of proof.', detail: 'Analysis, algebra, geometry, probability and numerical methods, taught with an emphasis on rigorous argument rather than calculation.' },
  { name: 'Environmental Science', slug: 'environmental-science', subject: 'natural-sciences', blurb: 'How natural systems work, and how human activity changes them.', detail: 'Ecology, climate science, hydrology, soil and atmospheric science, pollution and environmental policy, with substantial field and laboratory work.' },
  { name: 'Biotechnology', slug: 'biotechnology', subject: 'natural-sciences', blurb: 'Using living systems and their components to make useful things.', detail: 'Molecular biology, genetic engineering, fermentation and bioprocessing, and the regulatory and ethical frameworks that govern the field.' },
  { name: 'Economics', slug: 'economics', subject: 'social-sciences', blurb: 'How societies allocate scarce resources, and why the outcomes are often not what anyone intended.', detail: 'Microeconomics, macroeconomics and econometrics form the core, with specialisation into development, labour, industrial organisation or finance. The quantitative content is substantial.' },
  { name: 'Psychology', slug: 'psychology', subject: 'social-sciences', blurb: 'The scientific study of mind and behaviour.', detail: 'Cognitive, developmental, social and biological psychology, with a strong grounding in research methods and statistics and an empirical project.' },
  { name: 'International Relations', slug: 'international-relations', subject: 'social-sciences', blurb: 'How states and other international actors interact, cooperate and conflict.', detail: 'International theory, security, political economy, diplomacy and international institutions, with a strong emphasis on argument and writing.' },
  { name: 'Sociology', slug: 'sociology', subject: 'social-sciences', blurb: 'The study of social life, structure and change.', detail: 'Social theory, stratification, qualitative and quantitative research methods, and substantive areas such as work, migration, family or crime.' },
  { name: 'Architecture', slug: 'architecture', subject: 'architecture-and-built-environment', blurb: 'The design of buildings, taught through studio and assessed by portfolio.', detail: 'Design studio at the centre, with structures, environmental design, history, theory and construction technology alongside it. Professional qualification typically requires further study and supervised practice beyond the first degree.' },
  { name: 'Urban Planning', slug: 'urban-planning', subject: 'architecture-and-built-environment', blurb: 'Shaping how cities grow, move and function.', detail: 'Spatial planning, transport, housing, planning law, urban economics and sustainability, with studio projects at neighbourhood and city scale.' },
  { name: 'Construction Management', slug: 'construction-management', subject: 'architecture-and-built-environment', blurb: 'Delivering built projects on time, on budget and safely.', detail: 'Project planning, cost management, contracts and procurement, site safety and building technology, often with an industrial placement.' },
  { name: 'Landscape Architecture', slug: 'landscape-architecture', subject: 'architecture-and-built-environment', blurb: 'Designing outdoor space, from a courtyard to a regional strategy.', detail: 'Site analysis, planting design, ecology, hydrology and design studio, with a growing emphasis on climate adaptation and water management.' },
];

export const COURSES: CourseFacts[] = [
  // ---------------------------------------------------------- Computer Science
  { name: 'BSc Computer Science', slug: 'bsc-computer-science', subject: 'computer-science', spec: 'software-engineering', level: 'UG', qualification: 'Bachelor of Science', shortName: 'BSc CS', durationMin: 3, durationMax: 4, featured: true,
    covers: 'A full undergraduate grounding in computation: algorithms and data structures, the theory of what machines can compute, operating systems, networks, databases and a great deal of programming, widening in later years into areas such as artificial intelligence, security or graphics.',
    work: 'Lectures and tutorials supported by continuous programming coursework, laboratory sessions and team projects, with a substantial individual project in the final year. Expect the mathematics — discrete mathematics, probability, linear algebra — to be genuinely load-bearing rather than decorative.',
    careers: 'Software engineering, data and machine learning, security, infrastructure and research, in essentially every industry. A strong final-year project is often what a first employer actually asks about.' },
  { name: 'MSc Computer Science', slug: 'msc-computer-science', subject: 'computer-science', level: 'PG', qualification: 'Master of Science', shortName: 'MSc CS', durationMin: 1, durationMax: 2, featured: true,
    covers: 'Advanced study across algorithms, systems, machine learning and software architecture, with specialisation through elective modules and an individual research or engineering dissertation.',
    work: 'Taught modules for the first two thirds and a substantial dissertation for the remainder. Many institutions offer conversion routes for graduates of other disciplines; these cover the foundations first and are a different programme from the standard route, so check which one you are applying to.',
    careers: 'Senior technical roles, specialist engineering, research and doctoral study.' },
  { name: 'MSc Artificial Intelligence', slug: 'msc-artificial-intelligence', subject: 'computer-science', spec: 'artificial-intelligence', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2, featured: true,
    covers: 'Search, knowledge representation, reasoning under uncertainty and the machine learning methods that now dominate the field, together with the ethics and safety questions that arise once these systems are deployed.',
    work: 'Mathematically demanding taught modules with substantial implementation coursework, followed by a research dissertation. A solid background in probability, linear algebra and programming is assumed rather than taught.',
    careers: 'Machine learning engineering, applied research, robotics and AI-focused product development.' },
  { name: 'MSc Machine Learning', slug: 'msc-machine-learning', subject: 'computer-science', spec: 'machine-learning', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Supervised, unsupervised and reinforcement learning, deep neural networks, probabilistic modelling and the practical questions of generalisation, evaluation and bias that separate a working model from a demonstration.',
    work: 'Heavily quantitative, with implementation-led assignments and a research dissertation. Strong mathematics is a prerequisite rather than an advantage.',
    careers: 'Machine learning engineering, quantitative research, applied science roles and doctoral study.' },
  { name: 'MSc Cybersecurity', slug: 'msc-cybersecurity', subject: 'computer-science', spec: 'cybersecurity', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Cryptography, network and systems security, secure software development, digital forensics and incident response, alongside the governance and legal frameworks that constrain all of it.',
    work: 'Laboratory-intensive, with practical attack and defence exercises in controlled environments, and a dissertation. Good programmes teach offence as well as defence, on the principle that you cannot protect what you do not understand.',
    careers: 'Security engineering, penetration testing, security architecture, incident response and governance and compliance roles.' },
  { name: 'MSc Software Engineering', slug: 'msc-software-engineering', subject: 'computer-science', spec: 'software-engineering', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Architecture, requirements, design patterns, testing strategy, continuous delivery and the process of building software in a team that other people will maintain after you leave.',
    work: 'Project-led, usually including a substantial team project run to something close to professional practice, followed by an individual dissertation.',
    careers: 'Senior software engineering, technical leadership, architecture and engineering management.' },
  { name: 'MSc Distributed Systems and Cloud Computing', slug: 'msc-distributed-systems-and-cloud-computing', subject: 'computer-science', spec: 'computer-networks-and-distributed-systems', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Concurrency, consistency, fault tolerance, distributed storage and the architecture of systems that must keep working while parts of them fail.',
    work: 'Systems-heavy implementation coursework on real infrastructure, with a dissertation. Comfort with operating systems and networking is assumed.',
    careers: 'Platform and infrastructure engineering, site reliability engineering and backend architecture.' },
  { name: 'MSc Human-Computer Interaction', slug: 'msc-human-computer-interaction', subject: 'computer-science', spec: 'human-computer-interaction', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Interaction design, user research methods, usability evaluation, accessibility and the cognitive psychology that explains why interfaces succeed or fail.',
    work: 'A mixture of design studio, empirical study and prototyping, with research involving real participants and a dissertation.',
    careers: 'User experience research and design, product design and accessibility consultancy.' },
  { name: 'BSc Information Technology', slug: 'bsc-information-technology', subject: 'computer-science', level: 'UG', qualification: 'Bachelor of Science', durationMin: 3, durationMax: 4,
    covers: 'The applied side of computing: systems administration, networking, databases, web and enterprise application development, and the management of IT in an organisation.',
    work: 'More applied and less theoretical than a computer science degree, with heavier laboratory and project content and often an industrial placement.',
    careers: 'Systems and network administration, IT consultancy, database administration and enterprise application development.' },
  { name: 'PhD Computer Science', slug: 'phd-computer-science', subject: 'computer-science', level: 'PHD', qualification: 'Doctor of Philosophy', durationMin: 3, durationMax: 5,
    covers: 'An original contribution to computing knowledge, pursued through independent research under supervision and defended in a thesis.',
    work: 'Largely self-directed research with regular supervision, alongside publishing, conference presentation and often some teaching. Admission usually depends on a research proposal and on finding a supervisor whose interests match yours.',
    careers: 'Academic research and teaching, industrial research laboratories and specialist technical leadership.' },
  // ----------------------------------------------------------------- Engineering
  { name: 'BEng Mechanical Engineering', slug: 'beng-mechanical-engineering', subject: 'engineering', spec: 'mechanical-engineering', level: 'UG', qualification: 'Bachelor of Engineering', durationMin: 3, durationMax: 4, featured: true,
    covers: 'Statics and dynamics, thermodynamics, fluid mechanics, materials, manufacturing and machine design, built on a substantial mathematics foundation.',
    work: 'Lectures with heavy laboratory and computer-aided design content, a design-and-build project most years, and a major individual project in the final year.',
    careers: 'Design, manufacturing, energy, automotive and aerospace engineering. Professional registration usually requires a period of supervised practice after graduation.' },
  { name: 'MSc Mechanical Engineering', slug: 'msc-mechanical-engineering', subject: 'engineering', spec: 'mechanical-engineering', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Advanced mechanics, computational modelling, thermofluids and materials, with specialisation into areas such as energy systems, manufacturing or automotive engineering.',
    work: 'Taught modules with simulation and laboratory work, followed by a research or industry-linked dissertation.',
    careers: 'Specialist design and analysis roles, research and development, and consultancy.' },
  { name: 'BEng Electrical and Electronic Engineering', slug: 'beng-electrical-and-electronic-engineering', subject: 'engineering', spec: 'electrical-and-electronic-engineering', level: 'UG', qualification: 'Bachelor of Engineering', durationMin: 3, durationMax: 4,
    covers: 'Circuit theory, signals and systems, electromagnetics, control, power electronics, digital design and embedded systems.',
    work: 'Laboratory work runs throughout, from discrete circuits in the first year to embedded and power systems later, with a substantial final-year project.',
    careers: 'Power and energy, electronics design, telecommunications, embedded systems and control engineering.' },
  { name: 'MSc Electrical Engineering', slug: 'msc-electrical-engineering', subject: 'engineering', spec: 'electrical-and-electronic-engineering', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Advanced power systems, control, communications, signal processing and embedded design, with specialisation by elective.',
    work: 'Taught modules with laboratory and simulation work, followed by a dissertation often carried out with an industrial partner.',
    careers: 'Power systems, renewable energy, telecommunications, semiconductors and control engineering.' },
  { name: 'BEng Civil Engineering', slug: 'beng-civil-engineering', subject: 'engineering', spec: 'civil-engineering', level: 'UG', qualification: 'Bachelor of Engineering', durationMin: 3, durationMax: 4,
    covers: 'Structural analysis and design, geotechnics, hydraulics, transportation, materials and construction management.',
    work: 'Design projects, laboratory testing, surveying and field work, with a strong emphasis from the start on codes of practice, safety factors and professional responsibility.',
    careers: 'Structural and civil design consultancies, construction, transport and water infrastructure.' },
  { name: 'MSc Structural Engineering', slug: 'msc-structural-engineering', subject: 'engineering', spec: 'civil-engineering', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Advanced structural analysis, the behaviour of steel, concrete and composite structures, dynamics, and design for seismic and wind loading.',
    work: 'Analysis-heavy taught modules using professional software, with a design-led dissertation.',
    careers: 'Structural design consultancies, bridge and building engineering and specialist analysis roles.' },
  { name: 'BEng Chemical Engineering', slug: 'beng-chemical-engineering', subject: 'engineering', spec: 'chemical-engineering', level: 'UG', qualification: 'Bachelor of Engineering', durationMin: 3, durationMax: 4,
    covers: 'Mass and energy balances, transport phenomena, reaction engineering, separation processes, process control and plant design.',
    work: 'Laboratory and pilot-plant work alongside process simulation, culminating in a large team design project that is the defining piece of work in most such degrees.',
    careers: 'Process engineering in chemicals, pharmaceuticals, energy, food and water treatment.' },
  { name: 'MSc Aerospace Engineering', slug: 'msc-aerospace-engineering', subject: 'engineering', spec: 'aerospace-engineering', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Aerodynamics, propulsion, flight mechanics, aerospace structures and control systems, with options in space systems or aircraft design.',
    work: 'Computational fluid dynamics and structural simulation alongside wind tunnel work, with a substantial design or research dissertation.',
    careers: 'Aircraft and spacecraft design, propulsion, defence and aerospace research.' },
  { name: 'MSc Robotics and Autonomous Systems', slug: 'msc-robotics-and-autonomous-systems', subject: 'engineering', spec: 'robotics-and-mechatronics', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2, featured: true,
    covers: 'Kinematics and dynamics, sensing and perception, embedded control, computer vision, motion planning and machine learning for control.',
    work: 'Taught almost entirely through building: laboratory work with real hardware, team projects and a dissertation that usually involves a working system.',
    careers: 'Robotics engineering, autonomous vehicles, industrial automation and research.' },
  { name: 'BTech Engineering', slug: 'btech-engineering', subject: 'engineering', level: 'UG', qualification: 'Bachelor of Technology', shortName: 'BTech', durationMin: 4, durationMax: 4,
    covers: 'A four-year technology-focused engineering degree with a common foundation in mathematics, physics and engineering science before specialising into a chosen branch.',
    work: 'Semester-based with continuous assessment, extensive laboratory work, an industrial internship and a final-year project.',
    careers: 'Core engineering, technology and manufacturing roles, and a common route into postgraduate specialisation.' },
  { name: 'PhD Engineering', slug: 'phd-engineering', subject: 'engineering', level: 'PHD', qualification: 'Doctor of Philosophy', durationMin: 3, durationMax: 5,
    covers: 'An original research contribution in an engineering discipline, developed under supervision and defended in a thesis.',
    work: 'Independent research with regular supervision, usually including laboratory or computational work, publication and conference presentation.',
    careers: 'Academic and industrial research, advanced development roles and specialist consultancy.' },
  // ------------------------------------------------------ Business and Management
  { name: 'BBA Business Administration', slug: 'bba-business-administration', subject: 'business-and-management', level: 'UG', qualification: 'Bachelor of Business Administration', shortName: 'BBA', durationMin: 3, durationMax: 4,
    covers: 'Accounting, finance, marketing, operations, organisational behaviour and strategy, with specialisation in the later years.',
    work: 'Case studies, group projects and presentations dominate the assessment, often with an internship or consulting project built into the programme.',
    careers: 'Graduate schemes in consulting, finance, marketing and operations, and a foundation for later postgraduate management study.' },
  { name: 'MSc Finance', slug: 'msc-finance', subject: 'business-and-management', spec: 'finance', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2, featured: true,
    covers: 'Corporate finance, valuation, capital markets, derivatives, portfolio theory and risk management, with substantial quantitative content.',
    work: 'Technically demanding taught modules with modelling coursework, financial databases and often a research project or applied portfolio exercise.',
    careers: 'Investment banking, asset management, corporate finance, risk and financial analysis.' },
  { name: 'MSc Marketing', slug: 'msc-marketing', subject: 'business-and-management', spec: 'marketing', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Consumer behaviour, brand strategy, market research, pricing, digital channels and marketing analytics.',
    work: 'Case-led and project-based, frequently including a live client brief, with a dissertation or applied consultancy project.',
    careers: 'Brand and product marketing, market research, digital marketing and agency work.' },
  { name: 'MSc Supply Chain Management', slug: 'msc-supply-chain-management', subject: 'business-and-management', spec: 'supply-chain-and-operations', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Operations strategy, logistics, procurement, inventory and demand planning, quality management and the optimisation methods behind them.',
    work: 'Quantitative modelling alongside case analysis, often with a simulation exercise and an industry-linked project.',
    careers: 'Supply chain analysis and planning, logistics, procurement and operations management.' },
  { name: 'MSc International Business', slug: 'msc-international-business', subject: 'business-and-management', spec: 'international-business', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Foreign market entry, international finance and trade, cross-cultural management and the regulatory environments that shape them.',
    work: 'Case-led with substantial group work across mixed-nationality teams, which is a deliberate part of the design, and a final project or dissertation.',
    careers: 'International business development, export management, global operations and consultancy.' },
  { name: 'MSc Human Resource Management', slug: 'msc-human-resource-management', subject: 'business-and-management', spec: 'human-resource-management', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Employment relations, reward and performance systems, organisational development, employment law and workforce analytics.',
    work: 'Case-based and reflective, often aligned to a professional body’s standards, with a dissertation or workplace project.',
    careers: 'Human resources management, talent acquisition, learning and development and organisational consulting.' },
  { name: 'MSc Entrepreneurship and Innovation', slug: 'msc-entrepreneurship-and-innovation', subject: 'business-and-management', spec: 'entrepreneurship-and-innovation', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Opportunity identification, business modelling, venture finance, intellectual property and scaling, in both new ventures and established organisations.',
    work: 'Assessed largely through developing an actual venture proposition, with mentoring, pitching and a final business plan or dissertation.',
    careers: 'Founding a venture, early-stage company roles, venture capital, and innovation and strategy functions inside larger organisations.' },
  { name: 'Master of Business Administration', slug: 'master-of-business-administration', subject: 'business-and-management', level: 'MBA', qualification: 'Master of Business Administration', shortName: 'MBA', durationMin: 1, durationMax: 2, featured: true, modes: ['FULL_TIME', 'PART_TIME', 'ONLINE'],
    covers: 'A general management qualification covering finance, strategy, marketing, operations, leadership and organisational behaviour, designed for people who already have professional experience.',
    work: 'Intensive case study teaching with a great deal of group work, presentations and a consulting project or capstone. Most programmes expect several years of work experience before entry and the cohort’s experience is part of the teaching.',
    careers: 'General management, consulting, senior functional leadership and career transition into a new industry or function.' },
  { name: 'Postgraduate Diploma in Management', slug: 'postgraduate-diploma-in-management', subject: 'business-and-management', level: 'PGDM', qualification: 'Postgraduate Diploma in Management', shortName: 'PGDM', durationMin: 2, durationMax: 2,
    covers: 'A two-year management programme covering the functional areas of business with specialisation in the second year, taught in an applied and industry-oriented way.',
    work: 'Continuous assessment across trimesters or semesters, with a summer internship between years and a substantial live project.',
    careers: 'Management roles across consulting, finance, marketing, operations and general management.' },
  { name: 'PhD Management', slug: 'phd-management', subject: 'business-and-management', level: 'PHD', qualification: 'Doctor of Philosophy', durationMin: 3, durationMax: 5,
    covers: 'Original research in an area of management, organisational behaviour, strategy, finance or marketing, defended in a thesis.',
    work: 'Coursework in research method and theory in the early stages, followed by independent empirical research under supervision and publication.',
    careers: 'Academic posts in business schools, research roles and senior advisory and policy work.' },
  // ------------------------------------------------------------- Data and Analytics
  { name: 'MSc Data Science', slug: 'msc-data-science', subject: 'data-science-and-analytics', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2, featured: true,
    covers: 'Statistical inference, machine learning, data engineering, visualisation and the domain reasoning needed to turn a question into an analysis that answers it.',
    work: 'Project-heavy, working with real and therefore messy data, with programming coursework throughout and a dissertation often carried out with an external partner.',
    careers: 'Data science, analytics, machine learning engineering and quantitative research across sectors.' },
  { name: 'MSc Business Analytics', slug: 'msc-business-analytics', subject: 'data-science-and-analytics', spec: 'business-analytics', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Statistical modelling, forecasting, optimisation and visualisation, applied directly to decisions an organisation has to make.',
    work: 'Analytical coursework paired with case work and a consulting-style capstone. Communicating a result to people who will act on it is assessed as seriously as producing it.',
    careers: 'Business and product analytics, consulting, revenue management and decision science.' },
  { name: 'MSc Applied Statistics', slug: 'msc-applied-statistics', subject: 'data-science-and-analytics', spec: 'applied-statistics', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Inference, regression, experimental design, Bayesian methods, survival analysis and computational statistics.',
    work: 'Mathematically rigorous with substantial computational work, and a dissertation applying the methods to a real dataset.',
    careers: 'Statistical analysis in pharmaceuticals, government, finance and research, and doctoral study.' },
  { name: 'BSc Data Science', slug: 'bsc-data-science', subject: 'data-science-and-analytics', level: 'UG', qualification: 'Bachelor of Science', durationMin: 3, durationMax: 4,
    covers: 'Statistics, programming, databases and machine learning taken from foundations, with applied projects from early in the degree.',
    work: 'Coursework-heavy with continuous programming and analysis assignments, and a substantial final-year project.',
    careers: 'Analyst and junior data science roles, with a strong foundation for postgraduate specialisation.' },
  { name: 'MSc Bioinformatics', slug: 'msc-bioinformatics', subject: 'data-science-and-analytics', spec: 'bioinformatics', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Sequence analysis, genomics, structural biology, statistical genetics and the pipelines needed to handle data at that scale.',
    work: 'Computational laboratory work with genuine biological datasets, and a research dissertation usually embedded in a research group.',
    careers: 'Bioinformatics in pharmaceutical and biotechnology companies, genomics services and academic research.' },
  { name: 'MSc Data Engineering', slug: 'msc-data-engineering', subject: 'data-science-and-analytics', spec: 'big-data-engineering', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Distributed storage and processing, streaming architectures, data modelling, orchestration and the operational discipline of running a pipeline in production.',
    work: 'Systems-oriented implementation work on real infrastructure, with a dissertation building or evaluating a pipeline.',
    careers: 'Data engineering, platform engineering and analytics infrastructure roles.' },
  // ------------------------------------------------------------ Health and Medicine
  { name: 'Master of Public Health', slug: 'master-of-public-health', subject: 'health-and-medicine', spec: 'public-health', level: 'PG', qualification: 'Master of Public Health', shortName: 'MPH', durationMin: 1, durationMax: 2, featured: true,
    covers: 'Epidemiology, biostatistics, health policy, environmental health and health promotion, aimed at the health of populations rather than individual patients.',
    work: 'A quantitative core in epidemiology and statistics alongside policy and qualitative work, with a practicum or research dissertation.',
    careers: 'Public health agencies, non-governmental organisations, health policy, epidemiology and international health.' },
  { name: 'BSc Nursing', slug: 'bsc-nursing', subject: 'health-and-medicine', spec: 'nursing', level: 'UG', qualification: 'Bachelor of Science', durationMin: 3, durationMax: 4,
    covers: 'Anatomy and physiology, pharmacology, clinical skills and evidence-based practice, taught alongside extensive supervised clinical placement.',
    work: 'Roughly half the programme is spent in clinical placement in hospitals and community settings, on shift patterns including nights and weekends.',
    careers: 'Registered nursing practice across specialities. Practising requires registration with the professional regulator of the country you intend to work in, which is a separate process from graduating.' },
  { name: 'MSc Biomedical Science', slug: 'msc-biomedical-science', subject: 'health-and-medicine', spec: 'biomedical-science', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Cell biology, immunology, microbiology, genetics and clinical biochemistry, with advanced laboratory technique throughout.',
    work: 'Laboratory-intensive, with a substantial research project usually carried out inside an active research group.',
    careers: 'Clinical and research laboratories, pharmaceutical and biotechnology research, and doctoral study.' },
  { name: 'MPharm Pharmacy', slug: 'mpharm-pharmacy', subject: 'health-and-medicine', spec: 'pharmacy-and-pharmaceutical-sciences', level: 'PG', qualification: 'Master of Pharmacy', durationMin: 4, durationMax: 4,
    covers: 'Medicinal chemistry, pharmacology, pharmaceutics, pharmacy practice and law, as an integrated professional qualification.',
    work: 'Laboratory work and clinical placements throughout, with practical examinations alongside written ones.',
    careers: 'Community and hospital pharmacy, industry and regulatory roles. Registration requirements differ by country and usually include a period of supervised practice.' },
  { name: 'MSc Clinical Psychology', slug: 'msc-clinical-psychology', subject: 'health-and-medicine', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Psychopathology, assessment, therapeutic approaches and research methods, with supervised practice where the programme includes a clinical component.',
    work: 'Taught modules with case work and, on clinical routes, supervised placement. Research methods and a dissertation are standard.',
    careers: 'Clinical and counselling practice, mental health services and research. Licensure to practise is country-specific and usually requires further supervised training.' },
  { name: 'MSc Physiotherapy', slug: 'msc-physiotherapy', subject: 'health-and-medicine', spec: 'physiotherapy-and-rehabilitation', level: 'PG', qualification: 'Master of Science', durationMin: 2, durationMax: 3,
    covers: 'Musculoskeletal, neurological and cardiorespiratory practice, exercise science and manual therapy.',
    work: 'Practical skills teaching alongside extensive supervised clinical placement across different settings.',
    careers: 'Physiotherapy practice in hospitals, clinics and sport. Registration with the relevant professional body is required to practise.' },
  // ------------------------------------------------------------------------- Law
  { name: 'LLB Bachelor of Laws', slug: 'llb-bachelor-of-laws', subject: 'law', level: 'UG', qualification: 'Bachelor of Laws', shortName: 'LLB', durationMin: 3, durationMax: 4,
    covers: 'Contract, tort, criminal, constitutional, property and European or international law, taught through cases and statutes.',
    work: 'Reading-intensive, with assessment by essay, problem question and examination, and mooting as a normal part of the experience.',
    careers: 'Legal practice, corporate and in-house roles, policy and compliance. Qualifying to practise is jurisdiction-specific and requires further local steps.' },
  { name: 'LLM International Law', slug: 'llm-international-law', subject: 'law', spec: 'international-law', level: 'PG', qualification: 'Master of Laws', shortName: 'LLM', durationMin: 1, durationMax: 2,
    covers: 'Treaty law, international institutions, dispute resolution, humanitarian and international criminal law.',
    work: 'Seminar-based with heavy reading and long written work, culminating in a dissertation.',
    careers: 'International organisations, diplomacy, human rights practice, international arbitration and academia.' },
  { name: 'LLM Commercial Law', slug: 'llm-commercial-law', subject: 'law', spec: 'commercial-and-corporate-law', level: 'PG', qualification: 'Master of Laws', durationMin: 1, durationMax: 2,
    covers: 'Company law, mergers and acquisitions, competition law, insolvency, financial regulation and international commercial contracts.',
    work: 'Seminar teaching around case law and transactions, with substantial written assessment and a dissertation.',
    careers: 'Corporate legal practice, in-house counsel, regulatory and compliance roles.' },
  { name: 'LLM Human Rights Law', slug: 'llm-human-rights-law', subject: 'law', spec: 'human-rights-law', level: 'PG', qualification: 'Master of Laws', durationMin: 1, durationMax: 2,
    covers: 'International and regional human rights instruments, enforcement mechanisms, refugee and asylum law, and litigation and advocacy practice.',
    work: 'Seminar-led with extensive reading, and often a clinical or advocacy component alongside the dissertation.',
    careers: 'Human rights organisations, international bodies, refugee and asylum practice and public interest litigation.' },
  { name: 'LLM Intellectual Property Law', slug: 'llm-intellectual-property-law', subject: 'law', spec: 'intellectual-property-law', level: 'PG', qualification: 'Master of Laws', durationMin: 1, durationMax: 2,
    covers: 'Patents, trade marks, copyright and design rights, licensing and the interaction between protection and competition.',
    work: 'Seminar-based, often with technically qualified classmates, and assessed by written work and a dissertation.',
    careers: 'Intellectual property practice, technology transfer, licensing and in-house counsel in technology and pharmaceuticals.' },
  // ------------------------------------------------------- Design and Creative Arts
  { name: 'BDes Graphic Design', slug: 'bdes-graphic-design', subject: 'design-and-creative-arts', spec: 'graphic-and-communication-design', level: 'UG', qualification: 'Bachelor of Design', durationMin: 3, durationMax: 4,
    covers: 'Typography, layout, brand identity, editorial and digital design, taught through studio projects.',
    work: 'Studio-based, with projects presented for structured criticism and a portfolio built across the degree that matters more than any single grade.',
    careers: 'Design studios, agencies, in-house brand teams and independent practice.' },
  { name: 'MA User Experience Design', slug: 'ma-user-experience-design', subject: 'design-and-creative-arts', spec: 'interaction-and-user-experience-design', level: 'PG', qualification: 'Master of Arts', durationMin: 1, durationMax: 2, featured: true,
    covers: 'User research, information architecture, prototyping, interface design and usability testing.',
    work: 'Project-based, producing a portfolio of case studies that document the reasoning behind each design rather than only the outcome.',
    careers: 'Product design, user experience research and design systems roles.' },
  { name: 'MA Animation and Visual Effects', slug: 'ma-animation-and-visual-effects', subject: 'design-and-creative-arts', spec: 'animation-and-visual-effects', level: 'PG', qualification: 'Master of Arts', durationMin: 1, durationMax: 2,
    covers: 'Movement fundamentals, 3D modelling, rigging, lighting, compositing and studio pipeline practice.',
    work: 'Studio-based production work, usually in crews, culminating in a finished piece and a showreel.',
    careers: 'Animation and visual effects studios, games, advertising and independent production.' },
  { name: 'BA Fashion Design', slug: 'ba-fashion-design', subject: 'design-and-creative-arts', spec: 'fashion-design', level: 'UG', qualification: 'Bachelor of Arts', durationMin: 3, durationMax: 4,
    covers: 'Pattern cutting, garment construction, textiles, illustration and collection development.',
    work: 'Studio and workshop based, with a final collection developed over the last year and usually shown publicly.',
    careers: 'Design roles with fashion houses and retailers, textile and product development, styling and independent labels.' },
  { name: 'BA Film and Media Production', slug: 'ba-film-and-media-production', subject: 'design-and-creative-arts', spec: 'film-and-media-production', level: 'UG', qualification: 'Bachelor of Arts', durationMin: 3, durationMax: 4,
    covers: 'Directing, cinematography, sound, editing and production management, alongside film history and theory.',
    work: 'Taught by making films in crews, with rotating roles so that you learn each craft from the inside, and a graduation film at the end.',
    careers: 'Film and television production, commercials, streaming content and independent production.' },
  // ------------------------------------------------------------- Natural Sciences
  { name: 'BSc Physics', slug: 'bsc-physics', subject: 'natural-sciences', spec: 'physics', level: 'UG', qualification: 'Bachelor of Science', durationMin: 3, durationMax: 4,
    covers: 'Classical and quantum mechanics, electromagnetism, thermodynamics, statistical physics and relativity, on a heavy mathematical foundation.',
    work: 'Problem sets every week, laboratory work throughout, and a research project in the final year. The mathematics is the programme, not a prerequisite to it.',
    careers: 'Research and doctoral study, engineering and technology, data analysis, finance and teaching.' },
  { name: 'MSc Physics', slug: 'msc-physics', subject: 'natural-sciences', spec: 'physics', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Advanced quantum theory, condensed matter, particle or astrophysics depending on specialisation, and computational methods.',
    work: 'Advanced taught modules with a substantial research project embedded in a research group.',
    careers: 'Doctoral research, national laboratories, industrial research and quantitative roles in finance and technology.' },
  { name: 'BSc Chemistry', slug: 'bsc-chemistry', subject: 'natural-sciences', spec: 'chemistry', level: 'UG', qualification: 'Bachelor of Science', durationMin: 3, durationMax: 4,
    covers: 'Organic, inorganic, physical and analytical chemistry, with spectroscopy and structural analysis throughout.',
    work: 'Very substantial laboratory time — often a full day or more each week — alongside lectures and problem work, with a research project in the final year.',
    careers: 'Chemical, pharmaceutical and materials industries, analytical laboratories, research and teaching.' },
  { name: 'BSc Mathematics', slug: 'bsc-mathematics', subject: 'natural-sciences', spec: 'mathematics', level: 'UG', qualification: 'Bachelor of Science', durationMin: 3, durationMax: 4,
    covers: 'Analysis, linear and abstract algebra, geometry, probability, statistics and numerical methods.',
    work: 'Weekly problem sets and a strong emphasis on rigorous proof rather than calculation. The shift from computing answers to proving statements is the main adjustment in the first year.',
    careers: 'Finance and actuarial work, data science, software, operational research, teaching and doctoral study.' },
  { name: 'MSc Environmental Science', slug: 'msc-environmental-science', subject: 'natural-sciences', spec: 'environmental-science', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Climate science, hydrology, ecology, pollution, environmental assessment and policy.',
    work: 'Field and laboratory work alongside taught modules and geographic information systems, with a research dissertation.',
    careers: 'Environmental consultancy, regulatory agencies, conservation organisations and climate policy.' },
  { name: 'MSc Biotechnology', slug: 'msc-biotechnology', subject: 'natural-sciences', spec: 'biotechnology', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Molecular biology, genetic engineering, fermentation and bioprocessing, and the regulatory framework around bioproducts.',
    work: 'Laboratory-intensive with a research project, often carried out with an industrial partner.',
    careers: 'Biotechnology and pharmaceutical research and production, agritech and regulatory affairs.' },
  // ------------------------------------------------------------- Social Sciences
  { name: 'BA Economics', slug: 'ba-economics', subject: 'social-sciences', spec: 'economics', level: 'UG', qualification: 'Bachelor of Arts', durationMin: 3, durationMax: 4,
    covers: 'Microeconomics, macroeconomics and econometrics, with options across development, labour, industrial organisation and finance.',
    work: 'A mixture of problem sets, essays and empirical work. The quantitative content is substantially heavier than most applicants expect.',
    careers: 'Economic consultancy, financial analysis, government and central banks, policy research and data analysis.' },
  { name: 'MSc Economics', slug: 'msc-economics', subject: 'social-sciences', spec: 'economics', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Advanced microeconomic and macroeconomic theory and econometrics, with field specialisation by elective.',
    work: 'Mathematically demanding, with problem sets, empirical projects and a dissertation. A strong quantitative background is assumed.',
    careers: 'Economic consultancy, central banks and ministries, international organisations and doctoral study.' },
  { name: 'BSc Psychology', slug: 'bsc-psychology', subject: 'social-sciences', spec: 'psychology', level: 'UG', qualification: 'Bachelor of Science', durationMin: 3, durationMax: 4,
    covers: 'Cognitive, developmental, social and biological psychology, with research methods and statistics running throughout.',
    work: 'Laboratory practicals, statistical analysis and an empirical final-year project. The statistics component surprises a great many applicants.',
    careers: 'Psychological practice with further training, research, human resources, user research, education and health services.' },
  { name: 'MA International Relations', slug: 'ma-international-relations', subject: 'social-sciences', spec: 'international-relations', level: 'PG', qualification: 'Master of Arts', durationMin: 1, durationMax: 2,
    covers: 'International theory, security studies, international political economy, diplomacy and international institutions.',
    work: 'Seminar-based with heavy reading and long essays, culminating in a dissertation.',
    careers: 'Diplomacy, international organisations, policy research, risk analysis and journalism.' },
  { name: 'MA Sociology', slug: 'ma-sociology', subject: 'social-sciences', spec: 'sociology', level: 'PG', qualification: 'Master of Arts', durationMin: 1, durationMax: 2,
    covers: 'Social theory, stratification, and qualitative and quantitative research methods applied to areas such as work, migration or crime.',
    work: 'Seminar teaching with methods training and an empirical dissertation involving original fieldwork or secondary analysis.',
    careers: 'Social research, policy, non-governmental organisations, public sector analysis and doctoral study.' },
  // ---------------------------------------------- Architecture and Built Environment
  { name: 'BArch Architecture', slug: 'barch-architecture', subject: 'architecture-and-built-environment', spec: 'architecture', level: 'UG', qualification: 'Bachelor of Architecture', durationMin: 3, durationMax: 5,
    covers: 'Design studio at the centre, with structures, environmental design, construction technology, history and theory around it.',
    work: 'Studio dominates the timetable and the workload, assessed by portfolio and design review. It is widely regarded as one of the most time-consuming undergraduate degrees.',
    careers: 'Architectural practice — though full professional qualification requires further study and a period of supervised practice — along with related design and consultancy roles.' },
  { name: 'MArch Architecture', slug: 'march-architecture', subject: 'architecture-and-built-environment', spec: 'architecture', level: 'PG', qualification: 'Master of Architecture', durationMin: 2, durationMax: 2,
    covers: 'Advanced design studio with a self-directed thesis project, supported by technology, professional practice and theory.',
    work: 'Studio-led and largely self-directed, with a major design thesis and public review.',
    careers: 'Architectural practice and specialist design roles; usually a required stage on the route to professional registration.' },
  { name: 'MSc Urban Planning', slug: 'msc-urban-planning', subject: 'architecture-and-built-environment', spec: 'urban-planning', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Spatial planning, transport, housing, planning law, urban economics and sustainability.',
    work: 'Studio projects at neighbourhood and city scale alongside taught modules, with a dissertation or planning practice project.',
    careers: 'Local and regional planning authorities, planning consultancy, transport planning and development.' },
  { name: 'MSc Construction Project Management', slug: 'msc-construction-project-management', subject: 'architecture-and-built-environment', spec: 'construction-management', level: 'PG', qualification: 'Master of Science', durationMin: 1, durationMax: 2,
    covers: 'Project planning and control, cost management, contracts and procurement, site safety and building technology.',
    work: 'Case and project-based, often accredited by a professional body, with an industry-linked dissertation.',
    careers: 'Project and construction management, quantity surveying, contract administration and development management.' },
];
